[package]
name = "cycling_signatures"
version = "0.1.0"
authors = ["Travis Casey"]
edition = "2024"
description = "Algebraic topological descriptions of recurrent motions in high-dimensional dynamical systems"
readme = "README.md"
repository = "https://github.com/TravisCasey/cycling-signatures"
license = "GPL-3.0-or-later"
keywords = ["homology", "topology", "dynamical systems"]
categories = ["mathematics"]
resolver = "3"

[dependencies]
chomp3rs = { git = "https://github.com/TravisCasey/CHomP3-rs.git", rev = "ba91cb5bfc530a5bd0115034452e674cbb749aab", version = "0.3.7", default-features = false }
serde = { version = "1.0.228", features = ["derive"], optional = true }
thiserror = "2.0.18"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
cast_lossless = "allow"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"
len_without_is_empty = "allow"
unreadable_literal = "allow"

[features]
serde = ["dep:serde", "chomp3rs/serde"]
rayon = ["chomp3rs/rayon"]
mpi = ["chomp3rs/mpi"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
