"""Type stubs for the compiled cycling-signatures extension module."""

from typing import TypeAlias

import numpy as np
from numpy.typing import NDArray

Segment: TypeAlias = range | tuple[int, int]

class FormatVersionMismatchError(Exception): ...

class Euclidean:
    def __init__(self) -> None: ...

class Chebyshev:
    def __init__(self) -> None: ...

class SphereBundle:
    def __init__(self, direction_weight: float) -> None: ...
    def direction_weight(self) -> float: ...

Metric: TypeAlias = Euclidean | Chebyshev | SphereBundle

class CubicSpline:
    def __init__(self, knots: NDArray[np.float64], values: NDArray[np.float64]) -> None: ...

class ChebyshevSphereBundleInterpolator:
    def __init__(self, inner: CubicSpline, cube_halfspan: int) -> None: ...
    def radius(self) -> float: ...

Interpolator: TypeAlias = CubicSpline | ChebyshevSphereBundleInterpolator

class HomologyClass:
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def to_array(self) -> NDArray[np.uint8]: ...

class Subspace:
    def rank(self) -> int: ...
    def num_generators(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def contains(self, homology_class: HomologyClass) -> bool: ...

class CycleComponent:
    def cycles(self) -> list[tuple[int, int]]: ...
    def homology_class(self) -> HomologyClass: ...

class CyclingSignature:
    def span(self) -> Subspace: ...
    def rank(self) -> int: ...
    def components(self) -> list[CycleComponent]: ...

class Trajectory:
    def __init__(self, points: NDArray[np.float64]) -> None: ...
    @staticmethod
    def resample(interpolator: Interpolator, metric: Metric, bound: float) -> Trajectory: ...
    def points(self) -> NDArray[np.float64]: ...
    def original_count(self) -> int: ...
    def fingerprint(self) -> int: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> Trajectory: ...

class EmbeddedTrajectory:
    def __init__(self, trajectory: Trajectory, metric: Metric) -> None: ...
    def signature(self, segment: Segment, threshold: float) -> CyclingSignature: ...
    def cycle_class(self, segment: Segment) -> HomologyClass: ...
    def bound(self) -> float: ...
    def fingerprint(self) -> int: ...
    def save(self, trajectory_path: str, cover_path: str) -> None: ...
    @staticmethod
    def load(trajectory_path: str, cover_path: str, metric: Metric) -> EmbeddedTrajectory: ...

class Cycle:
    def range(self) -> tuple[int, int]: ...
    def birth(self) -> float: ...
    def length(self) -> int: ...

class Component:
    def class_id(self) -> int: ...
    def coverage(self) -> tuple[int, int]: ...
    def cycles(self) -> list[Cycle]: ...
    def cycle_count(self) -> int: ...
    def longest_cycle(self) -> Cycle: ...
    def shortest_cycle(self) -> Cycle: ...

class CycleStorage:
    @staticmethod
    def build(
        embedded: EmbeddedTrajectory,
        segment: Segment,
        threshold: float,
        max_length: int,
    ) -> CycleStorage: ...
    def extent(self) -> tuple[int, int]: ...
    def fingerprint(self) -> int: ...
    def threshold(self) -> float: ...
    def max_length(self) -> int: ...
    def classes(self) -> list[HomologyClass]: ...
    def components(self) -> list[Component]: ...
    def component(self, component_id: int) -> Component: ...
    def homology_class(self, component_id: int) -> HomologyClass: ...
    def signature(self, segment: Segment) -> Subspace: ...
    def components_covering(self, point: int) -> list[int]: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> CycleStorage: ...

__all__ = [
    "Chebyshev",
    "ChebyshevSphereBundleInterpolator",
    "Component",
    "CubicSpline",
    "Cycle",
    "CycleComponent",
    "CycleStorage",
    "CyclingSignature",
    "EmbeddedTrajectory",
    "Euclidean",
    "FormatVersionMismatchError",
    "HomologyClass",
    "SphereBundle",
    "Subspace",
    "Trajectory",
]
