"""Type stubs for the compiled cycling-signatures extension module."""

import os
from typing import TypeAlias

import numpy as np
from numpy.typing import NDArray

Segment: TypeAlias = range | tuple[int, int]

class FormatVersionMismatchError(Exception): ...

class Euclidean:
    def __init__(self) -> None: ...
    def distance(self, point: NDArray[np.float64], other: NDArray[np.float64]) -> float: ...
    def distance_matrix(self, points: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

class SphereBundle:
    def __init__(self) -> None: ...
    def distance(self, point: NDArray[np.float64], other: NDArray[np.float64]) -> float: ...
    def distance_matrix(self, points: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

Metric: TypeAlias = Euclidean | SphereBundle

class CubicSpline:
    def __init__(self, knots: NDArray[np.float64], values: NDArray[np.float64]) -> None: ...
    def sample(self, parameter: float) -> NDArray[np.float64]: ...
    def knots(self) -> NDArray[np.float64]: ...

class SphereBundleInterpolator:
    def __init__(self, inner: CubicSpline, direction_radius: float) -> None: ...
    def direction_radius(self) -> float: ...
    def sample(self, parameter: float) -> NDArray[np.float64]: ...

Interpolator: TypeAlias = CubicSpline | SphereBundleInterpolator

class HomologyClass:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __xor__(self, other: HomologyClass) -> HomologyClass: ...
    def __repr__(self) -> str: ...
    def is_zero(self) -> bool: ...
    def nonzero_indices(self) -> list[int]: ...
    def to_array(self) -> NDArray[np.uint8]: ...

class Subspace:
    def rank(self) -> int: ...
    def num_generators(self) -> int: ...
    def basis(self) -> list[HomologyClass]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def contains(self, homology_class: HomologyClass) -> bool: ...

class CyclingSignature:
    def span(self) -> Subspace: ...
    def rank(self) -> int: ...
    def rank_at(self, threshold: float) -> int: ...
    def span_at(self, threshold: float) -> Subspace: ...
    def births(self) -> list[float]: ...
    def classes(self) -> list[HomologyClass]: ...
    def threshold_max(self) -> float: ...
    def num_generators(self) -> int: ...
    def __repr__(self) -> str: ...

class Trajectory:
    def __init__(
        self, points: NDArray[np.float64], parameters: NDArray[np.float64] | None = None
    ) -> None: ...
    @staticmethod
    def resample(
        interpolator: Interpolator,
        metric: Metric,
        spacing: float,
    ) -> Trajectory: ...
    def downsample(self, metric: Metric, spacing: float) -> Trajectory: ...
    def resolution(self, metric: Metric) -> float: ...
    def points(self) -> NDArray[np.float64]: ...
    def parameters(self) -> NDArray[np.float64]: ...
    def __len__(self) -> int: ...
    def dimension(self) -> int: ...
    def fingerprint(self) -> int: ...
    def save(self, path: str | os.PathLike[str]) -> None: ...
    @staticmethod
    def load(path: str | os.PathLike[str]) -> Trajectory: ...

class CubicalCover:
    def __init__(self, trajectory: Trajectory, *, parallel: bool = True) -> None: ...
    def fingerprint(self) -> int: ...
    def __len__(self) -> int: ...
    def cubes(self) -> NDArray[np.int64]: ...
    def dimension(self) -> int: ...
    def num_generators(self) -> int: ...
    def save(self, path: str | os.PathLike[str]) -> None: ...
    @staticmethod
    def load(path: str | os.PathLike[str]) -> CubicalCover: ...

class EmbeddedTrajectory:
    def __init__(self, trajectory: Trajectory, cover: CubicalCover, metric: Metric) -> None: ...
    @staticmethod
    def from_interpolator(
        interpolator: Interpolator,
        metric: Metric,
        resample_spacing: float,
        downsample_spacing: float,
        *,
        parallel: bool = True,
    ) -> EmbeddedTrajectory: ...
    def signature(
        self, segment: Segment, threshold: float, *, parallel: bool = True
    ) -> CyclingSignature: ...
    def cycle_class(self, segment: Segment) -> HomologyClass: ...
    def resolution(self) -> float: ...
    def trajectory(self) -> Trajectory: ...
    def cover(self) -> CubicalCover: ...
    def metric(self) -> Metric: ...
    def __len__(self) -> int: ...
    def fingerprint(self) -> int: ...
    def save(
        self,
        embedded_path: str | os.PathLike[str],
        trajectory_path: str | os.PathLike[str],
        cover_path: str | os.PathLike[str],
    ) -> None: ...
    @staticmethod
    def load(
        embedded_path: str | os.PathLike[str],
        trajectory_path: str | os.PathLike[str],
        cover_path: str | os.PathLike[str],
    ) -> EmbeddedTrajectory: ...

class Cycle:
    def range(self) -> tuple[int, int]: ...
    def birth(self) -> float: ...
    def length(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class Component:
    def class_id(self) -> int: ...
    def coverage(self) -> tuple[int, int]: ...
    def cycles(self) -> list[Cycle]: ...
    def cycle_count(self) -> int: ...
    def longest_cycle(self) -> Cycle: ...
    def shortest_cycle(self) -> Cycle: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Cycle: ...
    def __repr__(self) -> str: ...

class CycleStorage:
    @staticmethod
    def build(
        embedded: EmbeddedTrajectory,
        segment: Segment,
        max_length: int,
        threshold: float,
        *,
        parallel: bool = True,
    ) -> CycleStorage: ...
    def extent(self) -> tuple[int, int]: ...
    def fingerprint(self) -> int: ...
    def threshold(self) -> float: ...
    def max_length(self) -> int: ...
    def num_generators(self) -> int: ...
    def classes(self) -> list[HomologyClass]: ...
    def components(self) -> list[Component]: ...
    def component(self, component_id: int) -> Component: ...
    def homology_class(self, component_id: int) -> HomologyClass: ...
    def signature(self, segment: Segment) -> CyclingSignature: ...
    def components_covering(self, point: int) -> list[int]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Component: ...
    def __repr__(self) -> str: ...
    def save(self, path: str | os.PathLike[str]) -> None: ...
    @staticmethod
    def load(path: str | os.PathLike[str]) -> CycleStorage: ...

__all__ = [
    "Component",
    "CubicSpline",
    "CubicalCover",
    "Cycle",
    "CycleStorage",
    "CyclingSignature",
    "EmbeddedTrajectory",
    "Euclidean",
    "FormatVersionMismatchError",
    "HomologyClass",
    "SphereBundle",
    "SphereBundleInterpolator",
    "Subspace",
    "Trajectory",
]
