"""Type stubs for the compiled cycling-signatures extension module."""

import os
from typing import TypeAlias

import numpy as np
from numpy.typing import NDArray

Segment: TypeAlias = range | tuple[int, int]

class FormatVersionMismatchError(Exception): ...

class Euclidean:
    def __init__(self) -> None: ...
    def distance(self, point: NDArray[np.float64], other: NDArray[np.float64]) -> float: ...
    def distance_matrix(self, points: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

class SphereBundle:
    def __init__(self, radius_floor: int) -> None: ...
    def radius_floor(self) -> int: ...
    def distance(self, point: NDArray[np.float64], other: NDArray[np.float64]) -> float: ...
    def distance_matrix(self, points: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

Metric: TypeAlias = Euclidean | SphereBundle

class CubicSpline:
    def __init__(self, knots: NDArray[np.float64], values: NDArray[np.float64]) -> None: ...

class ChebyshevSphereBundleInterpolator:
    def __init__(self, inner: CubicSpline, radius_floor: int) -> None: ...
    def radius(self) -> float: ...

Interpolator: TypeAlias = CubicSpline | ChebyshevSphereBundleInterpolator

class HomologyClass:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def is_zero(self) -> bool: ...
    def to_array(self) -> NDArray[np.uint8]: ...

class Subspace:
    def rank(self) -> int: ...
    def num_generators(self) -> int: ...
    def basis(self) -> list[HomologyClass]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def contains(self, homology_class: HomologyClass) -> bool: ...

class CyclingSignature:
    def span(self) -> Subspace: ...
    def rank(self) -> int: ...
    def rank_at(self, threshold: float) -> int: ...
    def span_at(self, threshold: float) -> Subspace: ...
    def births(self) -> list[float]: ...
    def classes(self) -> list[HomologyClass]: ...
    def threshold_max(self) -> float: ...
    def num_generators(self) -> int: ...
    def __repr__(self) -> str: ...

class Trajectory:
    def __init__(self, points: NDArray[np.float64]) -> None: ...
    @staticmethod
    def resample(interpolator: Interpolator, metric: Metric, bound: float) -> Trajectory: ...
    def points(self) -> NDArray[np.float64]: ...
    def original_count(self) -> int: ...
    def fingerprint(self) -> int: ...
    def save(self, path: str | os.PathLike[str]) -> None: ...
    @staticmethod
    def load(path: str | os.PathLike[str]) -> Trajectory: ...

class EmbeddedTrajectory:
    def __init__(self, trajectory: Trajectory, metric: Metric) -> None: ...
    def signature(self, segment: Segment, threshold: float | None = None) -> CyclingSignature: ...
    def cycle_class(self, segment: Segment) -> HomologyClass: ...
    def bound(self) -> float: ...
    def adjacency_bound(self, segment: Segment, max_length: int) -> float: ...
    def fingerprint(self) -> int: ...
    def save(
        self, trajectory_path: str | os.PathLike[str], cover_path: str | os.PathLike[str]
    ) -> None: ...
    @staticmethod
    def load(
        trajectory_path: str | os.PathLike[str],
        cover_path: str | os.PathLike[str],
        metric: Metric,
    ) -> EmbeddedTrajectory: ...

class Cycle:
    def range(self) -> tuple[int, int]: ...
    def birth(self) -> float: ...
    def length(self) -> int: ...
    def __repr__(self) -> str: ...

class Component:
    def class_id(self) -> int: ...
    def coverage(self) -> tuple[int, int]: ...
    def cycles(self) -> list[Cycle]: ...
    def cycle_count(self) -> int: ...
    def longest_cycle(self) -> Cycle: ...
    def shortest_cycle(self) -> Cycle: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Cycle: ...
    def __repr__(self) -> str: ...

class CycleStorage:
    @staticmethod
    def build(
        embedded: EmbeddedTrajectory,
        segment: Segment,
        max_length: int,
        threshold: float | None = None,
    ) -> CycleStorage: ...
    def extent(self) -> tuple[int, int]: ...
    def fingerprint(self) -> int: ...
    def threshold(self) -> float: ...
    def adjacency_bound(self) -> float: ...
    def max_length(self) -> int: ...
    def num_generators(self) -> int: ...
    def classes(self) -> list[HomologyClass]: ...
    def components(self) -> list[Component]: ...
    def component(self, component_id: int) -> Component: ...
    def homology_class(self, component_id: int) -> HomologyClass: ...
    def signature(self, segment: Segment) -> CyclingSignature: ...
    def components_covering(self, point: int) -> list[int]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Component: ...
    def __repr__(self) -> str: ...
    def save(self, path: str | os.PathLike[str]) -> None: ...
    @staticmethod
    def load(path: str | os.PathLike[str]) -> CycleStorage: ...

__all__ = [
    "ChebyshevSphereBundleInterpolator",
    "Component",
    "CubicSpline",
    "Cycle",
    "CycleStorage",
    "CyclingSignature",
    "EmbeddedTrajectory",
    "Euclidean",
    "FormatVersionMismatchError",
    "HomologyClass",
    "SphereBundle",
    "Subspace",
    "Trajectory",
]
