[package]
name = "cycling-signatures-py"
version = "0.1.0"
authors = ["Travis Casey"]
edition = "2024"
description = "Python bindings for cycling-signatures"
license = "GPL-3.0-or-later"
publish = false

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
cycling_signatures = { path = "..", features = ["serde", "rayon"] }
pyo3 = { version = "0.28", features = ["abi3-py311", "extension-module"] }
numpy = "0.28"
rustc-hash = "2.1.3"

[lints]
workspace = true
